// ======================================================================
// Baseline catalog — Limon-IT Conditional Access baseline R26.6 (v3.x).
// One entry per baseline policy: CA number, canonical name, version, and
// the release tag it carries in the baseline package:
//   NEW = introduced in R26.6 · UP = updated in R26.6 · "" = carried over.
// The Baseline Policies tool matches the tenant's policies against this
// list by CA number and compares versions.
// ======================================================================
const BASELINE = {
  release: "R26.6",
  line: "v3.x",
  policies: [
    {"num": 0, "name": "CA000-GRANT-Global-IP-AnyApp-AnyPlatform-MFA-v1.0.1", "version": "1.0.1", "tag": "", "resources": "All resources", "grant": "Authentication strength: Multifactor authentication"},
    {"num": 1, "name": "CA001-BLOCK-Global-ASR-AnyApp-AnyPlatform-CountryWhitelist-v1.0.1", "version": "1.0.1", "tag": "", "resources": "All resources", "grant": "Block access"},
    {"num": 2, "name": "CA002-BLOCK-Global-IP-AnyApp-AnyPlatform-LegacyAuthentication-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "Block access"},
    {"num": 3, "name": "CA003-GRANT-Global-BP-RegisterOrJoin-AnyPlatform-MFA-v1.0", "version": "1.0", "tag": "", "resources": "Register or join devices", "grant": "Authentication strength: Multifactor authentication"},
    {"num": 4, "name": "CA004-BLOCK-Global-IP-AnyApp-AnyPlatform-DeviceCode-v1.0.1", "version": "1.0.1", "tag": "UP", "resources": "All resources", "grant": "Block access"},
    {"num": 5, "name": "CA005-SESSION-Global-DP-Office365-AnyPlatform-Unmanaged-AppEnforcedRestrictions-BlockDownload-v1.0", "version": "1.0", "tag": "", "resources": "Office 365", "grant": "No controls (grant)"},
    {"num": 6, "name": "CA006-GRANT-Global-DP-Office365-iOSenAndroid-RequireAppProtection-v1.0.1", "version": "1.0.1", "tag": "UP", "resources": "Office 365", "grant": "Require app protection policy"},
    {"num": 7, "name": "CA007-SESSION-Global-DP-AllApps-DesktopOnly-14D-session lifetime for managed devices v3.0", "version": "3.0", "tag": "UP", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 8, "name": "CA008-SESSION-GLOBAL-DP-AllApps-WinOrMac-3H session lifetime for unmanaged devices v1.0.1", "version": "1.0.1", "tag": "", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 9, "name": "CA009-SESSION-Global-IP-AllApps-AnyPlatform-NeverPersistentBrowser-NonManaged-v3.0", "version": "3.0", "tag": "UP", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 10, "name": "CA010-BLOCK-Global-IP-AnyApp-AnyPlatform-AuthenticationTransfer-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "Block access"},
    {"num": 11, "name": "CA011-SESSION-Global-DP-ExchangeOnline-AnyPlatform-Unmanaged-AppEnforcedRestrictions-BlockDownload-v1.0", "version": "1.0", "tag": "", "resources": "Office 365 Exchange Online", "grant": "No controls (grant)"},
    {"num": 12, "name": "CA012-BLOCK-Global-DP-O365-AnyPlatform-Block business critical apps for Moderate insider risk v3.0.1", "version": "3.0.1", "tag": "NEW", "resources": "Office 365", "grant": "Block access"},
    {"num": 13, "name": "CA013-BLOCK-Global-DP-AllApps-AnyPlatform-Block Elevated insider risk-v3.0.1", "version": "3.0.1", "tag": "NEW", "resources": "All resources", "grant": "Block access"},
    {"num": 14, "name": "CA014-GRANT-Global-IP-AllApps-AnyPlatform-HighUserRisk-v3.0.1", "version": "3.0.1", "tag": "NEW", "resources": "All resources", "grant": "Require risk remediation"},
    {"num": 15, "name": "CA015-SESSION-Global-IP-AllApps-AnyPlatform-HighSignInRisk-v3.0.1", "version": "3.0.1", "tag": "NEW", "resources": "All resources", "grant": "Authentication strength: Phishing-resistant MFA + TAP"},
    {"num": 16, "name": "CA016-SESSION-Global-DP-AllApps-MobileOnly-14D-session lifetime for managed devices-v3.0", "version": "3.0", "tag": "NEW", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 17, "name": "CA017-SESSION-Global-COMP-AllApps-AnyPlatform-Require TOU acceptance for Minor insider risk-v3.0.1", "version": "3.0.1", "tag": "NEW", "resources": "All resources", "grant": "Terms of use: Terms of use Internals Minor insider risk"},
    {"num": 99, "name": "CA099-BLOCK-Global-IdentityProtection-AllApps-AnyPlatform-Block-Non-persona-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "Block access"},
    {"num": 100, "name": "CA100-GRANT-Admins-IP-AdminPortals-AnyPlatform-MFA-v1.0.2", "version": "1.0.2", "tag": "", "resources": "Microsoft Admin Portals", "grant": "Authentication strength: Phishing-resistant MFA + TAP"},
    {"num": 101, "name": "CA101-GRANT-Admins-IP-AnyApp-AnyPlatform-MFA-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "Authentication strength: Phishing-resistant MFA + TAP"},
    {"num": 102, "name": "CA102-SESSION-Admins-IP-AllApps-AnyPlatform-SigninFrequency-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 103, "name": "CA103-SESSION-Admins-IP-AllApps-AnyPlatform-PersistentBrowser-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 104, "name": "CA104-GRANT-Admins-IP-AllApps-AnyPlatform-CombinedRegistration-v1.0", "version": "1.0", "tag": "", "resources": "Register security information", "grant": "Authentication strength: Phishing-resistant MFA + TAP"},
    {"num": 105, "name": "CA105-GRANT-Admins-IP-AllApps-AnyPlatform-LowMediumUserRisk-v3.0", "version": "3.0", "tag": "UP", "resources": "All resources", "grant": "Require risk remediation"},
    {"num": 106, "name": "CA106-SESSION-Admins-IP-AllApps-AnyPlatform-LowMediumSignInRisk-v3.0", "version": "3.0", "tag": "UP", "resources": "All resources", "grant": "Authentication strength: Phishing-resistant MFA + TAP"},
    {"num": 107, "name": "CA107-BLOCK-Admins-ASR-AllApps-AnyPlatform-BlockUnknownPlatforms-v1.0.1", "version": "1.0.1", "tag": "", "resources": "All resources", "grant": "Block access"},
    {"num": 108, "name": "CA108-GRANT-Admins-DAP-AllApps-iOSorAndroid-ApprovedApp-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "Require app protection policy"},
    {"num": 109, "name": "CA109-SESSION-Admins-ASR-AnyPlatform- Re-authenticateProtectedActions-v1.0.2", "version": "1.0.2", "tag": "UP", "resources": "Auth context: Protected Actions", "grant": "No controls (grant)"},
    {"num": 110, "name": "CA110-BLOCK-Admins-ASR-O365-AnyPlatform-Block access to Office 365 v1.0.1", "version": "1.0.1", "tag": "UP", "resources": "Office 365", "grant": "Block access"},
    {"num": 111, "name": "CA111-GRANT-Admins-IP-MicrosoftAzureManagement -AnyPlatform-StrongMFA-v3.0.1", "version": "3.0.1", "tag": "UP", "resources": "Azure Resource Manager", "grant": "Authentication strength: Phishing-resistant MFA + TAP"},
    {"num": 112, "name": "CA112-GRANT-Admins-MFA-IP-PIM-AnyPlatform-Require MFA for PIM elevation v1.0", "version": "1.0", "tag": "", "resources": "Auth context: Strong Authentication for PIM", "grant": "Authentication strength: Phishing-resistant MFA + TAP"},
    {"num": 200, "name": "CA200-GRANT-Internals-IP-AnyApp-AnyPlatform-MFA-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "Authentication strength: Multifactor authentication"},
    {"num": 201, "name": "CA201-GRANT-Internals-IP-AnyApp-AnyPlatform-MediumUserRisk-v3.0", "version": "3.0", "tag": "UP", "resources": "All resources", "grant": "Require risk remediation"},
    {"num": 202, "name": "CA202-GRANT-Internals-IP-AllApps-MobileOnly-SigninFrequency-14d-UnmanagedDevices-v3.0", "version": "3.0", "tag": "NEW", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 203, "name": "CA203-GRANT-Internals-ID-MicrosoftIntuneEnrollment-AnyPlatform-MFA-v1.0", "version": "1.0", "tag": "", "resources": "Microsoft Intune Enrollment", "grant": "Require multifactor authentication"},
    {"num": 204, "name": "CA204-BLOCK-Internals-ASR-AllApps-AnyPlatform-BlockUnknownPlatforms-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "Block access"},
    {"num": 205, "name": "CA205-GRANT-Internals-BP-AnyApp-Windows-Compliant-or-EHJ-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "Require device to be marked compliant"},
    {"num": 206, "name": "CA206-SESSION-Internals-IP-AllApps-AnyPlatform-PersistentBrowser-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 207, "name": "CA207-BLOCK-Internals-ASR-SelectedApps-AnyPlatform-v1.0", "version": "1.0", "tag": "", "resources": "Microsoft To-Do", "grant": "Block access"},
    {"num": 208, "name": "CA208-GRANT-Internals-BP-AnyApp-MacOS-Compliant-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "Require device to be marked compliant"},
    {"num": 209, "name": "CA209-SESSION-Internals-ASR-Exchange&Sharepoint-Windows-Enforce Token Protection for Exchange & SharePoint on Mobile & Desktop applications v1.0", "version": "1.0", "tag": "", "resources": "Office 365 Exchange Online, Office 365 SharePoint Online", "grant": "No controls (grant)"},
    {"num": 210, "name": "CA210-GRANT-Internals-IP-AllApps-AnyPlatform-CombineRegistration-v1.0", "version": "1.0", "tag": "", "resources": "Register security information", "grant": "Authentication strength: Multifactor authentication"},
    {"num": 211, "name": "CA211-GRANT-Internals-IP-AllApps-AnyPlatform-MediumSignInRisk-v3.0.1", "version": "3.0.1", "tag": "UP", "resources": "All resources", "grant": "Authentication strength: Multifactor authentication"},
    {"num": 212, "name": "CA212-GRANT-Internals-DAP-AllApps-iOSorAndroid-ApprovedApp-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "Require app protection policy"},
    {"num": 213, "name": "CA213-BLOCK-Internals-BP-AllApps-AnyPlatform-AllowHQLoginOnly-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "Block access"},
    {"num": 214, "name": "CA214-SESSION-Internals-DP-AllApps-AnyPlatform-MonitorSessionNonCompliant-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 215, "name": "CA215-BLOCK-Internals-CN-AllApps-WindowsOrMACOS-Require Global Secure Access client active v3.0.2", "version": "3.0.2", "tag": "NEW", "resources": "All resources", "grant": "Block access"},
    {"num": 300, "name": "CA300-GRANT-Externals-IP-AnyApp-AnyPlatform-MFA-v3.0.1", "version": "3.0.1", "tag": "NEW", "resources": "All resources", "grant": "Authentication strength: Multifactor authentication"},
    {"num": 301, "name": "CA301-GRANT-Externals-BP-AllApps-Windows/macOS-Compliant-v3.0.1", "version": "3.0.1", "tag": "NEW", "resources": "All resources", "grant": "Require device to be marked compliant"},
    {"num": 302, "name": "CA302-BLOCK-Externals-DP-AllApps-AnyPlatform-BlockNonCompliantDownload- v3.0.1", "version": "3.0.1", "tag": "NEW", "resources": "Office 365 SharePoint Online, Office 365 Exchange Online…", "grant": "No controls (grant)"},
    {"num": 303, "name": "CA303-GRANT-Externals-IP-AllApps-AnyPlatform-CombineRegistration- v3.0", "version": "3.0", "tag": "NEW", "resources": "Register security information", "grant": "Authentication strength: Multifactor authentication"},
    {"num": 304, "name": "CA304-GRANT-Externals-IP-AllApps-AnyPlatform-MediumSignInRisk- v3.0.1", "version": "3.0.1", "tag": "NEW", "resources": "All resources", "grant": "Authentication strength: Multifactor authentication"},
    {"num": 305, "name": "CA305-GRANT-Externals-IP-AnyApp-AnyPlatform-MediumUserRisk- v3.0", "version": "3.0", "tag": "NEW", "resources": "All resources", "grant": "Require risk remediation"},
    {"num": 306, "name": "CA306-GRANT-Externals-IP-MicrosoftIntuneEnrollment-AnyPlatform-MFA- v3.0", "version": "3.0", "tag": "NEW", "resources": "Microsoft Intune Enrollment", "grant": "Require multifactor authentication"},
    {"num": 307, "name": "CA307-GRANT-Externals-DAP-AllApps-iOSorAndroid-ApprovedApp- v3.0", "version": "3.0", "tag": "NEW", "resources": "All resources", "grant": "Require app protection policy"},
    {"num": 308, "name": "CA308-SESSION-Externals-DP-AllApps-AnyPlatform-MonitorSessionNonCompliant- v3.0", "version": "3.0", "tag": "NEW", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 309, "name": "CA309-BLOCK-Externals-ASR-SelectedApps-AnyPlatform-v3.0.1", "version": "3.0.1", "tag": "NEW", "resources": "Office 365", "grant": "Block access"},
    {"num": 310, "name": "CA310-GRANT-Externals-Compliance-CombinedRegistration-AnyPlatform-Require TOU for Security Info for Externals-v3.0", "version": "3.0", "tag": "NEW", "resources": "Register security information", "grant": "Terms of use: Terms of use for Externals"},
    {"num": 400, "name": "CA400-GRANT-GuestUsers-IP-AnyApp-AnyPlatform-MFA-v1.0.1", "version": "1.0.1", "tag": "UP", "resources": "All resources", "grant": "Authentication strength: Multifactor authentication"},
    {"num": 401, "name": "CA401-BLOCK-GuestUsers-ASR-AllApps-AnyPlatform-BlockNonGuestAppAccess-v1.0.1", "version": "1.0.1", "tag": "UP", "resources": "All resources", "grant": "Block access"},
    {"num": 402, "name": "CA402-SESSION-GuestUsers-IP-AllApps-AnyPlatform-SigninFrequency-v1.0.1", "version": "1.0.1", "tag": "UP", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 403, "name": "CA403-SESSION-Guests-IP-AllApps-AnyPlatform-PersistentBrowser-v1.0.1", "version": "1.0.1", "tag": "UP", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 404, "name": "CA404-BLOCK-Guests-ASR-SelectedApps-AnyPlatform-v1.0.1", "version": "1.0.1", "tag": "UP", "resources": "Microsoft Admin Portals", "grant": "Block access"},
    {"num": 405, "name": "CA405-SESSION-Guests-DP-AllApps-AnyPlatform-MonitorSessionNonCompliant-v1.0.1", "version": "1.0.1", "tag": "UP", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 406, "name": "CA406-BLOCK-GuestUsers-ASR-Office365-AnyPlatform-AllowOffice365-v3.0", "version": "3.0", "tag": "NEW", "resources": "All resources", "grant": "Block access"},
    {"num": 500, "name": "CA500-GRANT-G_Admin-TOU-Comp-CombinedRegistration-AnyPlatform-Require TOU for SecurityInfo-v3.0", "version": "3.0", "tag": "NEW", "resources": "Register security information", "grant": "Terms of use: Terms of use for Externals"},
    {"num": 501, "name": "CA501-BLOCK-G_Admin-ASR-O365-AnyPlatform-Block access to Office 365 v3.0.1", "version": "3.0.1", "tag": "NEW", "resources": "Office 365", "grant": "Block access"},
    {"num": 502, "name": "CA502-GRANT-G_Admin-IP-AdminPortals-AnyPlatform-MFA-v3.0.1", "version": "3.0.1", "tag": "NEW", "resources": "Microsoft Admin Portals", "grant": "Authentication strength: Phishing-resistant MFA + TAP"},
    {"num": 503, "name": "CA503-GRANT-G_Admin-IP-AnyApp-AnyPlatform-MFA-v3.0", "version": "3.0", "tag": "NEW", "resources": "All resources", "grant": "Authentication strength: Phishing-resistant MFA + TAP"},
    {"num": 504, "name": "CA504-SESSION-G_Admin-IP-AllApps-AnyPlatform-SigninFrequency-v3.0", "version": "3.0", "tag": "NEW", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 505, "name": "CA505-SESSION-G_Admin-IP-AllApps-AnyPlatform-PersistentBrowser-v3.0", "version": "3.0", "tag": "NEW", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 506, "name": "CA506-GRANT-G_Admin-MFA-IP-PIM-AnyPlatform-Require MFA for PIM elevation v3.0", "version": "3.0", "tag": "NEW", "resources": "Auth context: Strong Authentication for PIM", "grant": "No controls (grant)"},
    {"num": 507, "name": "CA507-GRANT-G_Admin-IP-AllApps-AnyPlatform-LowMediumSignInRisk-v3.0", "version": "3.0", "tag": "NEW", "resources": "All resources", "grant": "Authentication strength: Phishing-resistant MFA + TAP"},
    {"num": 508, "name": "CA508-BLOCK-G_Admin-IP-AnyApp-AnyPlatform-LowMediumUserRisk-v3.0", "version": "3.0", "tag": "NEW", "resources": "All resources", "grant": "Require risk remediation"},
    {"num": 600, "name": "CA600-BLOCK-MSA-BP-AllApps-AnyPlatform-BlockUntrustedLocations-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "Block access"},
    {"num": 601, "name": "CA601-BLOCK-MSA-IP-AllApps-AnyPlatform-Block Medium & High user risk-v3.0", "version": "3.0", "tag": "UP", "resources": "All resources", "grant": "Block access"},
    {"num": 602, "name": "CA602-BLOCK-MSA-ASR-O365-AnyPlatform-BlockNonO365-v3.0.1", "version": "3.0.1", "tag": "UP", "resources": "All resources", "grant": "Block access"},
    {"num": 603, "name": "CA603-BLOCK-MSA-IP-AllApps-AnyPlatform-Block Medium & High sign-in risk v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "Block access"},
    {"num": 604, "name": "CA604-SESSION-MSA-DP-AllApps-AnyPlatform-Enforce CAE strict location v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 900, "name": "CA900-BLOCK-WorkloadIDs-Agents-IP-AnyApp-AnyPlatform-BLOCK-HighRiskAgent-v3.0.1", "version": "3.0.1", "tag": "NEW", "resources": "All resources", "grant": "Block access"},
    {"num": 901, "name": "CA901-BLOCK-WorkloadIDs-ASR-AllApps-AnyPlatform-Block untrusted locations v3.0", "version": "3.0", "tag": "NEW", "resources": "All resources", "grant": "Block access"},
    {"num": 902, "name": "CA902-BLOCK-WorkloadIDs-IP-AllApps-AnyPlatform-Block Medium & High-Service Principal risk-v3.0", "version": "3.0", "tag": "NEW", "resources": "All resources", "grant": "Block access"},
    {"num": 1000, "name": "CA1000-GRANT-DevOps-BP-AllApps-AnyPlatform-MFAfromUnamagedDevices-v1.0.1", "version": "1.0.1", "tag": "UP", "resources": "All resources", "grant": "Authentication strength: Phishing-resistant MFA + TAP"},
    {"num": 1001, "name": "CA1001-GRANT-DevOps-IP-AllApps-AnyPlatform-LowMediumSignInRisk-v3.0", "version": "3.0", "tag": "UP", "resources": "All resources", "grant": "Authentication strength: Phishing-resistant MFA + TAP"},
    {"num": 1002, "name": "CA1002-BLOCK-DevOps-IP-AnyApp-AnyPlatform-LowMediumUserRisk-v3.0", "version": "3.0", "tag": "UP", "resources": "All resources", "grant": "Block access"},
    {"num": 1003, "name": "CA1003-GRANT-DevOps-DAP-AllApps-iOSorAndroid-ApprovedApp-v1.0.1", "version": "1.0.1", "tag": "", "resources": "All resources", "grant": "Require app protection policy"},
    {"num": 1004, "name": "CA1004-BLOCK-DevOps-ASR-AllApps-AnyPlatform-BlockUnknownPlatforms-v1.0", "version": "1.0", "tag": "", "resources": "All resources", "grant": "Block access"},
    {"num": 1005, "name": "CA1005-BLOCK-DevOps-ASR-AzureDevops-AnyPlatform-NonTrustedLocations-v3.0.1", "version": "3.0.1", "tag": "UP", "resources": "Azure DevOps", "grant": "Block access"},
    {"num": 1006, "name": "CA1006-SESSION-DevOps-IP-AllApps-AnyPlatform-PersistentBrowser", "version": null, "tag": "", "resources": "All resources", "grant": "No controls (grant)"},
    {"num": 1007, "name": "CA1007-SESSION-Internals-ASR-Exchange&Sharepoint-Windows-Enforce Token Protection for Exchange & Sharepoint on Mobile & Desktop applications v1.0", "version": "1.0", "tag": "", "resources": "Office 365 Exchange Online, Office 365 SharePoint Online", "grant": "No controls (grant)"},
    {"num": 1008, "name": "CA1008-GRANT-DevOps-IP-AllApps-AnyPlatform-CombinedRegistration-v3.0", "version": "3.0", "tag": "NEW", "resources": "Register security information", "grant": "Authentication strength: Multifactor authentication"},
    {"num": 1009, "name": "CA1009-BLOCK-DevOps-ASR-AzureDevops-AnyPlatform-BlockNonDevOpsPersona-v3.0", "version": "3.0", "tag": "NEW", "resources": "Azure DevOps", "grant": "Block access"},
    {"num": 1100, "name": "CA1100-GRANT-E-Admins-IP-AllApps-AnyPlatform-Emergency_access1-v3.0", "version": "3.0", "tag": "UP", "resources": "All resources", "grant": "Authentication strength: Phishing-resistant MFA + TAP"},
    {"num": 1101, "name": "CA1101-GRANT-E-Admins-IP-AllApps-AnyPlatform-Emergency_access2-v3.0", "version": "3.0", "tag": "UP", "resources": "All resources", "grant": "Authentication strength: Phishing-resistant MFA + TAP"},
    {"num": 1102, "name": "CA1102-BLOCK-E-Admins-ASR-AllApps-AnyPlatform-Nontrustedlocations-v3.0", "version": "3.0", "tag": "UP", "resources": "All resources", "grant": "Block access"},
    {"num": 1103, "name": "CA1103-BLOCK-E-Admins-BP-AnyApp-NonWindowsPlatform-v3.0", "version": "3.0", "tag": "UP", "resources": "All resources", "grant": "Block access"},
    {"num": 1104, "name": "CA1104-BLOCK-E-Admins-ASR-AnyApp-NonBrowserClients-v3.0", "version": "3.0", "tag": "UP", "resources": "All resources", "grant": "Block access"},
    {"num": 1105, "name": "CA1105-SESSION-E-Admins-ASR-AllApps-SIF3h-NeverPersistent-v3.0", "version": "3.0", "tag": "UP", "resources": "All resources", "grant": "No controls (grant)"},
  ],
};
