// ======================================================================
// BRANDING — the one file to edit when you fork this.
//
// Everything the site shows about *who made it* lives here: the product
// name, the organisation, the logos, the colours, the footer. Nothing else
// in the app hard-codes them; index.html carries this file's defaults as
// plain markup so the page still reads correctly before JavaScript runs,
// and applyBranding() (js/app.js) overwrites it from this object at start-up.
//
// To rebrand a fork:
//   1. Edit the fields below.
//   2. Drop your own SVG/PNG into assets/ and point `logo` and `favicon` at
//      them (a 1:1 mark works best — it is drawn at 34px and 76px).
//   3. Set `clientId` in js/authConfig.js to YOUR Entra app registration and
//      put your own host in its redirect URIs (New-EncaAppRegistration.ps1
//      does both for you).
//   4. Put your host in the CNAME file if you publish on GitHub Pages.
//
// What is deliberately NOT here:
//   · Exports (Word/PDF/PNG) stay neutral by design — they carry the
//     customer's tenant branding, never the tool's. Only a one-line
//     "generated by" credit is added, built from `name` and `host` below.
//   · The baseline catalogs (js/baselineData.js, js/groupTemplates.js) are
//     content, not branding — fork those separately if your naming
//     convention differs.
// ======================================================================
const BRANDING = {
  // Product
  name: "ENCA",                                   // short name, shown in the header chip and footer
  longName: "Conditional Access Baseline Tools",  // descriptive line next to it
  expansion: "Entra Conditional Access",          // what the short name stands for ("" to hide)

  // Organisation
  org: "Limon-IT",
  // The org name is drawn as two parts so the second half can take the accent
  // colour ("Limon-<span>IT</span>"). Set `orgSplit` to "" for one flat word.
  orgSplit: "IT",
  orgUrl: "https://limon-it.nl",
  copyright: "© 2026 Limon-IT",

  // Where this deployment lives. Shown in the header and in the one-line
  // credit at the bottom of every Markdown export. No protocol.
  host: "enca.limon-it.nl",

  // Assets (relative to index.html)
  logo: "assets/logo-mark-light.svg",
  logoDark: "assets/logo-mark-dark.svg",
  favicon: "assets/favicon.svg",

  // Sign-in screen
  loginTitle: "",            // "" → `${name} — ${longName}`
  loginBlurb: "Sign in with your Microsoft Entra account to browse, document, analyze and back up your Conditional Access baseline — including the newest policy settings.",

  // Optional colour overrides, written straight onto :root as CSS variables.
  // Leave empty to keep the stylesheet's palette. The three that carry the
  // identity are enough for most forks; css/app.css has the full set.
  colors: {
    // "--green": "#1e4729",
    // "--accent2": "#3f7a24",
    // "--lemon": "#f7d65a",
  },
};

// ======================================================================
// Per-audience looks. A deployment can serve more than one organisation:
// when the signed-in account's UPN matches an override, the app's CHROME
// (header, colours, login screen, favicon) switches to that audience's
// brand — and each override gets its own front door at /<key>/ (a static
// page that opens the app pre-branded, e.g. enca.limon-it.nl/pvm).
//
// What an override does NOT change, by design:
//   · Exports keep the neutral credit built from BRANDING above — the tool
//     stays ENCA regardless of whose colours the chrome wears.
//   · Only identity colours are overridden (greens → the audience's hue,
//     the lemon accent) — background/surface/ink stay theme-managed, so
//     light and dark mode both keep working.
//
// To add an audience: append an entry here, drop a logo in assets/<key>/,
// and copy pvm/index.html to <key>/index.html with the same key.
// ======================================================================
const BRAND_OVERRIDES = [
  {
    key: "pvm",
    label: "Perfetti Van Melle",
    match: /@pvmict\.com$/i,               // UPN domain(s) that get this look on sign-in
    brand: {
      org: "Perfetti Van Melle",
      orgSplit: "",
      orgUrl: "https://www.perfettivanmelle.com",
      logo: "assets/pvm/logo.png",       // the official wide wordmark
      logoDark: "assets/pvm/logo.png",   // transparent background — works on dark too
      logoWide: true,                    // draw at natural aspect, not the 1:1 mark size
      hideOrgName: true,                 // the wordmark already says it — no text next to the logo
      favicon: "assets/pvm/favicon.png",
      loginTitle: "",
      loginBlurb: "Sign in with your Perfetti Van Melle account (@pvmict.com) to browse, document, analyze and back up the Conditional Access baseline.",
      // Sampled from the official logo: navy #202a6f, red #c80b1a. The navy
      // family replaces the greens EVERYWHERE — identity colours and the
      // green-tinted canvas (ink, backgrounds, borders) alike — per theme, so
      // no Limon green survives in either mode. The logo's red stays in the
      // logo (red controls would read as "destructive"); gold keeps the warm
      // action accent. Theme-scoped palettes are injected as a stylesheet by
      // applyBranding(), so light/dark/auto all resolve correctly.
      colorsLight: {
        "--ink": "#151b3e", "--green": "#202a6f", "--green-deep": "#141a4a", "--accent2": "#3a48a8",
        "--lemon": "#f2a900", "--lemon-deep": "#cf8d00",
        "--muted": "#5c6584", "--border": "#dde1ee", "--bg": "#f3f5fa", "--soft": "#ecf0f8",
        "--hover": "#fafbfe", "--line": "#eef1f8", "--soft2": "#f6f8fc", "--glow": "#d7ddf2",
        "--shadow": "0 10px 30px rgba(21,27,62,.10)",
        "--hl": "rgba(58,72,168,.10)", "--hl2": "rgba(58,72,168,.22)",
        "--ghost-bd": "#1b2358", "--na": "#ced4e2", "--faint": "#bdc4da", "--on-deep-mute": "#c8cde2",
      },
      colorsDark: {
        "--ink": "#e8ecf7", "--green": "#8fa0e8", "--green-deep": "#141a4a", "--accent2": "#9db1f2",
        "--lemon": "#f2c14e", "--lemon-deep": "#d9a32e",
        "--muted": "#93a0c4", "--border": "#252d52", "--surface": "#151b36", "--bg": "#0d1226",
        "--soft": "#1a2142", "--hover": "#1f2749", "--line": "#202950", "--soft2": "#111834",
        "--glow": "#202a6f55", "--shadow": "0 10px 30px rgba(0,0,0,.35)",
        "--hl": "rgba(143,160,232,.12)", "--hl2": "rgba(143,160,232,.25)",
      },
    },
  },
];
const BrandOverrides = {
  forUpn: (upn) => BRAND_OVERRIDES.find((o) => o.match.test(String(upn || ""))) || null,
  byKey: (k) => BRAND_OVERRIDES.find((o) => o.key === k) || null,
};

// Small helpers so no other file has to assemble these strings. Every export
// footer and on-screen credit goes through here.
// The look currently on screen. BRANDING is the deployment's own identity;
// when a per-audience override is active (see BRAND_OVERRIDES) the chrome
// wears that instead — and anything drawing a mark needs the override, not the
// base. applyBranding() sets this; everything else reads it.
//
// Deliberately NOT used by Brand.title / Brand.credit: exports carry the
// neutral product credit whoever is signed in, which is the whole point of
// the override only changing chrome.
let ACTIVE_BRANDING = null;

const Brand = {
  // the active look, falling back to the deployment's own
  get current() { return ACTIVE_BRANDING || BRANDING; },
  setActive(b) { ACTIVE_BRANDING = b || null; },

  // "ENCA — Conditional Access Baseline Tools"
  get title() { return BRANDING.longName ? `${BRANDING.name} — ${BRANDING.longName}` : BRANDING.name; },
  // "ENCA · Conditional Access Baseline Tools · Limon-IT" — the <title>
  get pageTitle() { return [BRANDING.name, BRANDING.longName, BRANDING.org].filter(Boolean).join(" · "); },
  // "ENCA — Conditional Access Baseline Tools (enca.limon-it.nl)"
  get credit() { return BRANDING.host ? `${Brand.title} (${BRANDING.host})` : Brand.title; },
  // The line every Markdown export ends its header with.
  generatedBy(verb) {
    const t = new Date().toISOString().replace("T", " ").slice(0, 16);
    return `${verb || "Generated"} ${t} UTC by ${Brand.credit}.`;
  },
  // Short form for the PNG/PDF corner: "ENCA · enca.limon-it.nl"
  get stamp() { return [BRANDING.name, BRANDING.host].filter(Boolean).join(" · "); },
};
