// ======================================================================
// BRANDING — the one file to edit when you fork this.
//
// Everything the site shows about *who made it* lives here: the product
// name, the organisation, the logos, the colours, the footer. Nothing else
// in the app hard-codes them; index.html carries this file's defaults as
// plain markup so the page still reads correctly before JavaScript runs,
// and applyBranding() (js/app.js) overwrites it from this object at start-up.
//
// To rebrand a fork:
//   1. Edit the fields below.
//   2. Drop your own SVG/PNG into assets/ and point `logo` and `favicon` at
//      them (a 1:1 mark works best — it is drawn at 34px and 76px).
//   3. Set `clientId` in js/authConfig.js to YOUR Entra app registration and
//      put your own host in its redirect URIs (New-EncaAppRegistration.ps1
//      does both for you).
//   4. Put your host in the CNAME file if you publish on GitHub Pages.
//
// What is deliberately NOT here:
//   · Exports (Word/PDF/PNG) stay neutral by design — they carry the
//     customer's tenant branding, never the tool's. Only a one-line
//     "generated by" credit is added, built from `name` and `host` below.
//   · The baseline catalogs (js/baselineData.js, js/groupTemplates.js) are
//     content, not branding — fork those separately if your naming
//     convention differs.
// ======================================================================
const BRANDING = {
  // Product
  name: "ENCA",                                   // short name, shown in the header chip and footer
  longName: "Conditional Access Baseline Tools",  // descriptive line next to it
  expansion: "Entra Conditional Access",          // what the short name stands for ("" to hide)

  // Organisation
  org: "Limon-IT",
  // The org name is drawn as two parts so the second half can take the accent
  // colour ("Limon-<span>IT</span>"). Set `orgSplit` to "" for one flat word.
  orgSplit: "IT",
  orgUrl: "https://limon-it.nl",
  copyright: "© 2026 Limon-IT",

  // Where this deployment lives. Shown in the header and in the one-line
  // credit at the bottom of every Markdown export. No protocol.
  host: "enca.limon-it.nl",

  // The publisher's OWN pre-production host. Everything that is neither `host`
  // nor this is somebody else's copy, and the app says SELF-HOSTED there rather
  // than BETA — a deployment an organisation stood up deliberately is not a
  // test build, and calling it one teaches people to ignore the ribbon.
  //
  // Hostname only, no protocol and no path: the beta site is served from a
  // project path under the Pages domain, and location.hostname is what the
  // comparison has to work on. Like `host`, this is deliberately NOT reachable
  // from selfhost-branding.json — a copy that could name itself the publisher's
  // beta host could hide that it is a copy.
  betaHost: "nurejev.github.io",

  // Assets (relative to index.html)
  // The ENCA mark — the app's own logo, not Limon-IT's. Built the same way as
  // the other Limon-IT product marks (see TUNO): TRANSPARENT, so it carries on
  // any header colour without a tile behind it, and framed twice from one
  // drawing. The mark keeps the orbit ring; the favicon is cropped to the
  // inner disc, because a browser tab renders it at 16-32px and the ring is
  // just noise at that size. The dark variant is swapped in by CSS rather than
  // by script, so it is right before the app has even booted.
  //
  // The ?v= is not decoration: these filenames previously held the Limon-IT
  // mark, so without it a returning visitor keeps seeing the old logo out of
  // cache. Bump it with the build whenever the artwork changes.
  logo: "assets/logo-mark-light.svg?v=25163",
  logoDark: "assets/logo-mark-dark.svg?v=25163",
  favicon: "assets/favicon.svg?v=25163",

  // Sign-in screen
  loginTitle: "",            // "" → `${name} — ${longName}`
  loginBlurb: "Sign in with your Microsoft Entra account to browse, document, analyze and back up your Conditional Access baseline — including the newest policy settings.",

  // Optional colour overrides, written straight onto :root as CSS variables.
  // Leave empty to keep the stylesheet's palette. The three that carry the
  // identity are enough for most forks; css/app.css has the full set.
  colors: {
    // "--green": "#1e4729",
    // NOTE --green-deep is load-bearing beyond text: the dimmed backdrop
    // behind every dialog is color-mix(--green-deep 55%, transparent), so a
    // brand that overrides --green should override --green-deep too or its
    // dialogs will dim in the neutral brand's deep green.
    // "--accent2": "#3f7a24",
    // "--lemon": "#f7d65a",
  },
};

// ======================================================================
// Per-audience looks. A deployment can serve more than one organisation:
// when the signed-in account's UPN matches an override, the app's CHROME
// (header, colours, login screen, favicon) switches to that audience's
// brand — and each override gets its own front door at /<key>/ (a static
// page that opens the app pre-branded, e.g. <host>/<key>).
//
// What an override does NOT change, by design:
//   · Exports keep the neutral credit built from BRANDING above — the tool
//     stays ENCA regardless of whose colours the chrome wears.
//   · Only identity colours are overridden (greens → the audience's hue,
//     the lemon accent) — background/surface/ink stay theme-managed, so
//     light and dark mode both keep working.
//
// To add an audience: append an entry here — key, label, a `match` regex
// for the UPN domain(s) that get the look on sign-in, and a `brand` object
// (any BRANDING field above, plus per-theme colorsLight/colorsDark palettes
// injected as a stylesheet by applyBranding()). An optional front door at
// /<key>/ is a static page that opens the app with ?brand=<key>.
//
// The list ships EMPTY. The one entry it carried — a customer demo —
// was a demo of the mechanism and was retired in build 25196; the same
// look now lives on as a selfhost-branding.json (kept out of the repo),
// which is the self-hosting way to wear a brand without forking at all
// (js/selfhost.js, SELF-HOSTING.md). The machinery stays: forUpn/byKey,
// ?brand= and the stylesheet injection all work the day an entry returns.
// ======================================================================
const BRAND_OVERRIDES = [];
const BrandOverrides = {
  forUpn: (upn) => BRAND_OVERRIDES.find((o) => o.match.test(String(upn || ""))) || null,
  byKey: (k) => BRAND_OVERRIDES.find((o) => o.key === k) || null,
};

// Small helpers so no other file has to assemble these strings. Every export
// footer and on-screen credit goes through here.
// The look currently on screen. BRANDING is the deployment's own identity;
// when a per-audience override is active (see BRAND_OVERRIDES) the chrome
// wears that instead — and anything drawing a mark needs the override, not the
// base. applyBranding() sets this; everything else reads it.
//
// Deliberately NOT used by Brand.title / Brand.credit: exports carry the
// neutral product credit whoever is signed in, which is the whole point of
// the override only changing chrome.
let ACTIVE_BRANDING = null;

const Brand = {
  // the active look, falling back to the deployment's own
  get current() { return ACTIVE_BRANDING || BRANDING; },
  setActive(b) { ACTIVE_BRANDING = b || null; },

  // "ENCA — Conditional Access Baseline Tools"
  get title() { return BRANDING.longName ? `${BRANDING.name} — ${BRANDING.longName}` : BRANDING.name; },
  // "ENCA · Conditional Access Baseline Tools · Limon-IT" — the <title>
  get pageTitle() { return [BRANDING.name, BRANDING.longName, BRANDING.org].filter(Boolean).join(" · "); },
  // "ENCA — Conditional Access Baseline Tools (enca.limon-it.nl)"
  get credit() { return BRANDING.host ? `${Brand.title} (${BRANDING.host})` : Brand.title; },
  // The line every Markdown export ends its header with.
  generatedBy(verb) {
    const t = new Date().toISOString().replace("T", " ").slice(0, 16);
    return `${verb || "Generated"} ${t} UTC by ${Brand.credit}.`;
  },
  // Short form for the PNG/PDF corner: "ENCA · enca.limon-it.nl"
  get stamp() { return [BRANDING.name, BRANDING.host].filter(Boolean).join(" · "); },
};
