// ======================================================================
// BRANDING — the one file to edit when you fork this.
//
// Everything the site shows about *who made it* lives here: the product
// name, the organisation, the logos, the colours, the footer. Nothing else
// in the app hard-codes them; index.html carries this file's defaults as
// plain markup so the page still reads correctly before JavaScript runs,
// and applyBranding() (js/app.js) overwrites it from this object at start-up.
//
// To rebrand a fork:
//   1. Edit the fields below.
//   2. Drop your own SVG/PNG into assets/ and point `logo` and `favicon` at
//      them (a 1:1 mark works best — it is drawn at 34px and 76px).
//   3. Set `clientId` in js/authConfig.js to YOUR Entra app registration and
//      put your own host in its redirect URIs (New-EncaAppRegistration.ps1
//      does both for you).
//   4. Put your host in the CNAME file if you publish on GitHub Pages.
//
// What is deliberately NOT here:
//   · Exports (Word/PDF/PNG) stay neutral by design — they carry the
//     customer's tenant branding, never the tool's. Only a one-line
//     "generated by" credit is added, built from `name` and `host` below.
//   · The baseline catalogs (js/baselineData.js, js/groupTemplates.js) are
//     content, not branding — fork those separately if your naming
//     convention differs.
// ======================================================================
const BRANDING = {
  // Product
  name: "ENCA",                                   // short name, shown in the header chip and footer
  longName: "Conditional Access Baseline Tools",  // descriptive line next to it
  expansion: "Entra Conditional Access",          // what the short name stands for ("" to hide)

  // Organisation
  org: "Limon-IT",
  // The org name is drawn as two parts so the second half can take the accent
  // colour ("Limon-<span>IT</span>"). Set `orgSplit` to "" for one flat word.
  orgSplit: "IT",
  orgUrl: "https://limon-it.nl",
  copyright: "© 2026 Limon-IT",

  // Where this deployment lives. Shown in the header and in the one-line
  // credit at the bottom of every Markdown export. No protocol.
  host: "enca.limon-it.nl",

  // Assets (relative to index.html)
  logo: "assets/logo-mark-light.svg",
  logoDark: "assets/logo-mark-dark.svg",
  favicon: "assets/favicon.svg",

  // Sign-in screen
  loginTitle: "",            // "" → `${name} — ${longName}`
  loginBlurb: "Sign in with your Microsoft Entra account to browse, document, analyze and back up your Conditional Access baseline — including the newest policy settings.",

  // Optional colour overrides, written straight onto :root as CSS variables.
  // Leave empty to keep the stylesheet's palette. The three that carry the
  // identity are enough for most forks; css/app.css has the full set.
  colors: {
    // "--green": "#1e4729",
    // "--accent2": "#3f7a24",
    // "--lemon": "#f7d65a",
  },
};

// Small helpers so no other file has to assemble these strings. Every export
// footer and on-screen credit goes through here.
const Brand = {
  // "ENCA — Conditional Access Baseline Tools"
  get title() { return BRANDING.longName ? `${BRANDING.name} — ${BRANDING.longName}` : BRANDING.name; },
  // "ENCA · Conditional Access Baseline Tools · Limon-IT" — the <title>
  get pageTitle() { return [BRANDING.name, BRANDING.longName, BRANDING.org].filter(Boolean).join(" · "); },
  // "ENCA — Conditional Access Baseline Tools (enca.limon-it.nl)"
  get credit() { return BRANDING.host ? `${Brand.title} (${BRANDING.host})` : Brand.title; },
  // The line every Markdown export ends its header with.
  generatedBy(verb) {
    const t = new Date().toISOString().replace("T", " ").slice(0, 16);
    return `${verb || "Generated"} ${t} UTC by ${Brand.credit}.`;
  },
  // Short form for the PNG/PDF corner: "ENCA · enca.limon-it.nl"
  get stamp() { return [BRANDING.name, BRANDING.host].filter(Boolean).join(" · "); },
};
