// ======================================================================
// Export: PNG (single card) and combined PDF (cover + cards + matrix).
// Cards are rendered off-screen at a fixed 1100px width for consistency.
// ======================================================================
const Exporter = (() => {
  const A4 = { w: 297, h: 210 }; // landscape, mm
  const MARGIN = 10;

  function stage(html) {
    const el = document.createElement("div");
    el.className = "export-stage";
    el.innerHTML = html;
    document.body.appendChild(el);
    return el;
  }

  async function nodeToPng(node) {
    // double render works around fonts/images not ready on first pass
    await htmlToImage.toPng(node, { pixelRatio: 2, backgroundColor: "#ffffff" });
    return htmlToImage.toPng(node, { pixelRatio: 2, backgroundColor: "#ffffff" });
  }

  function download(dataUrl, filename) {
    const a = document.createElement("a");
    a.href = dataUrl; a.download = filename; a.click();
  }

  const safe = (s) => s.replace(/[^\w\- ]+/g, "").trim().replace(/\s+/g, "-").slice(0, 60);

  async function policyPng(p, tenantName) {
    const st = stage(Render.card(p, tenantName));
    try {
      const url = await nodeToPng(st.firstElementChild);
      download(url, `${p.seq}-${safe(p.name)}.png`);
    } finally { st.remove(); }
  }

  function addCover(pdf, tenantName, count) {
    pdf.setFillColor(18, 51, 31); // green-deep
    pdf.rect(0, 0, A4.w, A4.h, "F");
    pdf.setFillColor(30, 71, 41);
    pdf.rect(0, A4.h - 40, A4.w, 40, "F");
    pdf.setDrawColor(247, 214, 90); pdf.setLineWidth(1.2);
    pdf.line(MARGIN, 96, 110, 96);
    pdf.setTextColor(247, 214, 90);
    pdf.setFontSize(13); pdf.setFont("helvetica", "bold");
    pdf.text("LIMON-IT · CA DOC", MARGIN, 40);
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(30);
    pdf.text("Conditional Access", MARGIN, 70);
    pdf.text("Documentation", MARGIN, 84);
    pdf.setFontSize(13); pdf.setFont("helvetica", "normal");
    pdf.setTextColor(198, 214, 202);
    pdf.text(`${tenantName || "Tenant"}  ·  ${count} policies  ·  ${new Date().toISOString().slice(0, 10)}`, MARGIN, 110);
    pdf.setFontSize(10);
    pdf.text("Generated by CA Doc — cadoc.limon-it.nl", MARGIN, A4.h - 18);
  }

  async function addImagePaged(pdf, node) {
    // renders node and adds it, slicing vertically over multiple pages if needed
    const url = await nodeToPng(node);
    const img = new Image();
    await new Promise((res, rej) => { img.onload = res; img.onerror = rej; img.src = url; });
    const availW = A4.w - MARGIN * 2, availH = A4.h - MARGIN * 2;
    const scale = availW / img.width;
    const totalH = img.height * scale;
    if (totalH <= availH) {
      pdf.addImage(url, "PNG", MARGIN, MARGIN, availW, totalH);
      return;
    }
    // slice
    const sliceHpx = availH / scale;
    const canvas = document.createElement("canvas");
    canvas.width = img.width;
    const ctx = canvas.getContext("2d");
    let y = 0, first = true;
    while (y < img.height) {
      const h = Math.min(sliceHpx, img.height - y);
      canvas.height = h;
      ctx.fillStyle = "#fff"; ctx.fillRect(0, 0, canvas.width, h);
      ctx.drawImage(img, 0, y, img.width, h, 0, 0, img.width, h);
      if (!first) pdf.addPage();
      pdf.addImage(canvas.toDataURL("image/png"), "PNG", MARGIN, MARGIN, availW, h * scale);
      y += h; first = false;
    }
  }

  async function policiesPdf(policies, tenantName, includeMatrix, onProgress) {
    const pdf = new jspdf.jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
    addCover(pdf, tenantName, policies.length);

    for (let i = 0; i < policies.length; i++) {
      onProgress?.(`Rendering ${policies[i].seq} (${i + 1}/${policies.length})…`);
      const st = stage(Render.card(policies[i], tenantName));
      try {
        pdf.addPage();
        await addImagePaged(pdf, st.firstElementChild);
        pdf.setFontSize(8); pdf.setTextColor(95, 122, 103);
        pdf.text(`${policies[i].seq} — ${policies[i].name}`.slice(0, 120), MARGIN, A4.h - 4);
      } finally { st.remove(); }
    }

    if (includeMatrix) {
      onProgress?.("Rendering settings matrix…");
      const st = stage(`<div class="matrix-wrap" style="width:2000px"><table class="matrix">${Render.matrix(policies)}</table></div>`);
      st.style.width = "2000px";
      try {
        pdf.addPage();
        await addImagePaged(pdf, st.firstElementChild);
      } finally { st.remove(); }
    }

    pdf.save(`ConditionalAccess-${safe(tenantName || "tenant")}-${new Date().toISOString().slice(0, 10)}.pdf`);
  }

  return { policyPng, policiesPdf };
})();
