// ======================================================================
// Build stamp. Shown on the sign-in screen and in the footer so you can
// tell at a glance whether the deployed site is the version you pushed —
// GitHub Pages and the browser cache can both lag a commit behind.
//
// `build` matches the ?v= cache-busting number on every asset URL in
// index.html; bump both together when releasing.
// ======================================================================
const APP_BUILD = {
  version: "1.0",
  build: 239,
  date: "2026-08-11",
  get label() { return `v${this.version}.${this.build}`; },
  get full() { return `${this.label} · ${this.date}`; },
};

// Per-tool versions, keyed by the tile id in index.html. Each tool moves at
// its own pace, so a tenant-side reviewer can tell which one changed since
// they last looked without diffing the whole app. Bump the tool you touched.
const TOOL_VERSIONS = {
  toolPolicies:     { v: "2.3", note: "list and summary say how many more include entries there are instead of showing only the first;usable on a phone — non-sticky toolbar, single-column policy cards, scrolling state filters, scrolling list table, two-row action bar;cards / list / settings matrix, persona grouping, dependency inspector, full-screen matrix, selection actions, delete with typed confirmation, per-policy what-if flow, per-persona apply flow, housekeeping (delete superseded Off versions)" },
  toolDocument:     { v: "1.4", note: "Word, PDF, PNG and PNG-bundle export with tenant branding" },
  toolAnalyze:      { v: "1.6", note: "users × policies impact matrix, group filters, standalone HTML report, scoped matrix columns" },
  toolGapCheck:     { v: "1.7", note: "scorecard pillars and signals are clickable and filter the findings list to their related categories (severity chips count the filtered view, ✕ chip or All clears);legacy-auth per-policy finding correlates with the tenant's dedicated block — LOW when an enabled tenant-wide block covers it, MEDIUM when the block is narrower, HIGH when there is none — and the scorecard signal mirrors it (100 full / 70 partial / 50 report-only / 0);Zero Trust scorecard (3 pillars, weighted 0-100 signals) on the summary and in the Markdown export; 7 new checks: risk-based-policy gaps, Microsoft-managed policy detection (incl. disabled phantom drafts), platform-scoping without an unknown-platform block, named-location hygiene, MFA client-app-type coverage, disabled resilience defaults, authentication-context / Protected Actions validation; bypass checks, persona × control matrix, deployed-but-Off state, Markdown export" },
  toolExclusions:   { v: "1.6", note: "exclusion × policy matrix (default, unmerged), effective-user view and risk review (governance flags per policy, patterns after Tiago S. Carvalho), click-to-filter rows and columns, group member list, CSV and Markdown" },
  toolValidator:    { v: "1.6", note: "per-policy sign-in simulation report ported from Jasper Baes' Conditional Access Validator — expected control per user/app/client/location/platform/risk, inverted 'no control' for excluded scope, report-only toggle, filter/search, Markdown export (no Maester code, representative placeholder users), click a policy name to open its card — out of BETA" },
  toolWhatIf:       { v: "1.0", note: "Entra Conditional Access What If tool re-implementation — simulate a sign-in (identity, resource, platform, client app, IP/country, device state, risks, auth flow) and get the policies that apply with their grant/session controls plus the policies that don't and the first unmet condition; named-location CIDR and country matching, Markdown export" },
  toolGroupUse:     { v: "1.0", note: "out of BETA — where an Entra group is actually used: 23 services across Entra ID (nesting, administrative units, directory roles incl. PIM eligibility, enterprise apps, group-based licensing, authentication methods policy, Conditional Access, access packages, admin-consent reviewers, registration state), Intune (enrolment restrictions, compliance, configuration profiles, scripts, app protection, app configuration, app assignments, Autopilot, Windows update profiles), Microsoft 365 (M365 group / Team) and Azure RBAC across subscriptions and management groups; one group or user, or a tenant-wide sweep with an unused-groups view; parent-group inheritance shown per hit; per-area consent; Markdown, standalone HTML and CSV export. 0.2: sweep rows open a popup built from the sweep data instead of re-scanning (with Deep analyze for parent expansion), HTML report added, Intune scripts now request DeviceManagementScripts.Read.All and entitlement management uses single-level expands with a candidate ladder (both were failing), and every failure says which permission and which role it needs. 0.3: sweep can be narrowed by name prefix / suffix / substring, and drilling into a group keeps the sweep loaded behind a Back button. 0.4: default sweep scope is the groups Conditional Access actually assigns — taken from the policies already in memory, no directory enumeration — with dangling references (an id a policy names but the directory no longer has) kept and flagged; summary chips ride in a sticky strip so the counts and filters stay reachable on a long result. After Jasper Baes' Microsoft Cloud Group Analyzer" },
  toolCompare:      { v: "1.0", note: "two or more users side by side: per-policy assignment (included / excluded and why / not targeted) with differences flagged, group and role membership diff, optional What-If sign-in scenario evaluated per user, differences-only toggle, Markdown export — out of BETA" },
  toolAudit:        { v: "1.5", note: "directory audit log of Conditional Access changes — policy, named location, authentication strength/context and terms-of-use edits with a field-level diff of what moved, actor and IP, kind/action filters, 7/30/90-day window, Markdown export, JSON snapshot export/compare, summary view — out of BETA" },
  toolImpact:       { v: "0.3", note: "0.3: 1-hour and 4-hour ranges — check a fresh staged policy against the last hour instead of a whole day. 0.2: live progress while the window is read — running sign-in count, page number and elapsed time with a bar toward the record cap, so a large tenant's multi-minute read visibly moves (and survives switching tabs). BETA — the go-live forecast for report-only policies, from the sign-in log: per policy, who would be DENIED, who is interrupted for an extra step and who passes unchanged (reportOnlyFailure / reportOnlyInterrupted / reportOnlySuccess, with out-of-scope as the denominator's remainder); per user, the combined effect of everything in report-only at once, worst case first; verdict chips (would block / prompts only / no change / never in scope / no data — a staged policy with zero traffic is listed too, as the answer that should stop a go-live), distribution bar, per-user drill-down, 1/7/30-day window, Markdown export" },
  toolSignins:      { v: "1.6", note: "1-hour and 4-hour ranges for incident triage;search box suggests UPNs — the users and apps in the current result first, then the directory;Sign-ins (per sign-in) is the default view; usable on a phone (full-width search, swipeable policy chips, tighter cards); out of BETA; policy names open the policy card (as in List Policies); sticky policy label while scrolling an expanded policy's sign-ins; sign-in log × Conditional Access verdicts — sign-ins a policy failed (enforced) or would have failed (report-only, client-filtered and capped), grouped per policy with distinct users, affected apps and unmet grant controls; per-policy chips, user/app/IP search, 1/7/30-day window, one-click replay of a logged sign-in in What-If, CSV export (one line per sign-in × failing policy) and Markdown report" },
  toolBaseline:     { v: "1.8", note: "Limon-IT catalog, card and table views, number-clash detection, collapsible personas, catalog revision 2026-07-21, refresh, on-screen gap report" },
  toolBaselineJoey: { v: "1.1", note: "Joey Verlinden catalog 2026.6.1, verified against commit 38469a4" },
  toolMsLearn:      { v: "2.1", note: "findings whose whole remediation is an exclusion are suppressed when the policy already carries it (convention groups resolved before the checks run, not after); create builds from the bundled group template; CAB-SEC-U-TeamsSharedDevices recognised as canonical;17 documented checks, 14 buildable fixes, apply-in-tenant with service-principal creation and change report" },
  toolJson:         { v: "1.2", note: "policy zip including dependencies and terms-of-use PDFs" },
  toolProtect:      { v: "1.2", note: "several scoped administrators, comma-separated, each resolved and granted on its own with per-account outcomes in the report;scan on demand (▶ button) instead of on open, result persists across tab switches until an explicit rescan, a scan in flight survives navigation; standalone view of the exclusion-group protection workflow — restricted management administrative unit (create if missing or reuse), per-group protection status, optional AU-scoped Groups Administrator, explicit acknowledgement, Markdown report; the same workflow remains available as CA groups ⑥ Protect" },
  toolCaGroups:     { v: "2.4", note: "🧹 Archived groups housekeeping (delete the leftovers a recreate renamed aside, with policy-reference and member guards); recreate now carries the members across; disable nesting hidden on role-assignable groups, which already forbid it;④ Assign targets directory roles as well as groups — include and exclude, with Microsoft’s 14-role privileged set as a quick pick;⑥ Protect takes several scoped administrators (comma-separated);🚫 Disable group nesting (BETA): Entra's beta disableNesting on a persona group so no group can be added as a member — three-state detection (disabled / allowed / not reported, since a plain read does not return it), the in-place PATCH attempted AND verified by reading the value back, rename + recreate + move user members + repoint policies only if Entra refuses and only behind a second typed confirmation, and a hard block when the group already contains nested groups;⑥ Protect: restricted management administrative unit for the CA exclusion groups — per-group protection status, create/reuse the restricted AU (isMemberManagementRestricted, immutable), optional AU-scoped Groups Administrator, explicit acknowledgement, Markdown report; ⑤ Import members: bulk-add pilot users from a CSV (UPN + optional multi-persona column) with persona→group auto-mapping, membership pre-check, review-before-apply and a Markdown change report;baseline group check, creation, members × groups matrix, and policy assignment in one tool, per-group member scan, manual group builder, remove-group action, final confirm, assignment change report, pick-by-persona, TeamsSharedDevices template, per-row create, recreate-role-assignable, convert-to-dynamic (in place or rename + recreate + reassign)" },
  toolAuthCtx:      { v: "1.0", note: "out of BETA — manage the Conditional Access authentication contexts (c1-c99): list every defined context with publish state and the CA policies that enforce it, create in a free slot, rename, edit the description, publish / unpublish with one click, delete guarded by Graph's own rules (unpublished + unreferenced only, typed confirmation), free-slot count, Markdown export, demo mode. The id is treated as the immutable contract it is" },
  toolAuthStr:      { v: "0.2", note: "BETA — 0.2: Advanced options as in the portal — restrict Passkeys (FIDO2) to specific AAGUIDs (Microsoft Authenticator / Windows Hello presets or any custom AAGUID) and certificate-based authentication to specific issuer SKIs and policy OIDs, read via $expand, written via combinationConfigurations (create carries them inline; edit diffs POST/PATCH/DELETE); restrictions shown on the cards and in the Markdown report. manage the Conditional Access authentication strengths: the three built-in strengths read-only with their combinations, custom strengths created / renamed / re-combined (via Graph's dedicated updateAllowedCombinations action) / deleted when no policy grants them (typed confirmation), each strength classified phishing-resistant / MFA / allows-single-factor by its weakest combination, per-strength policy usage, combination picker grouped by class with the live catalog read from Graph (curated fallback), Markdown export, demo mode" },
  toolTou:          { v: "0.2", note: "PDFs actually load: the list endpoint never returns fileData, so each agreement is now fetched individually with $expand=files — languages and the ⭳ PDF download appear on the cards, and the edit dialog lists the current PDFs (language, default marker, view/download); create fixed: the POST carries only what the create API accepts (name, view-before-accepting, files) with per-device and re-accept applied in a follow-up PATCH, and Save now awaits the file reader so a fast Save cannot race the PDF upload;BETA — manage the terms-of-use agreements Conditional Access can require: every agreement with its behaviour settings (view-before-accepting, per-device acceptance, re-accept schedule, expiration), its PDFs per language with direct download, and the policies requiring it; create with a PDF upload (base64 inline per the Graph contract), edit the behaviour settings, per-agreement acceptance summary on demand (accepted / declined counts + latest, AgreementAcceptance.Read.All requested only then), delete blocked while any policy requires the agreement (dangling-grant protection) and typed-confirmed; Markdown export, demo mode. PDF replacement / extra languages deliberately not yet in scope" },
  toolRecycle:      { v: "1.0", note: "out of BETA — the Conditional Access recycle bin: recently deleted policies AND named locations (both share the 30-day soft-delete window), each with what it did, its state at deletion, when it went and how many days it has left; expiring-soon filter; one-click restore with the right guard rails — a policy that was On at deletion enforces again the moment it is restored, so that restore demands a typed RESTORE, name collisions with the live set are flagged, and restoring a trusted location warns that All-trusted policies follow it again immediately; the live policy set reloads after a policy restore so every other tool sees it; Markdown export, demo mode" },
  toolLocations:    { v: "1.4", note: "named locations inventory with policy usage; create/edit/delete IP-range and country locations, CIDR + ISO-code validation, trusted-flag impact warning, typed confirm when a referenced location is deleted, card grid + table view, per-location report with full policy usage, per-location and inventory Markdown, JSON config snapshot + compare — out of BETA" },
  toolState:        { v: "1.0", note: "On / report-only / Off switching" },
  toolImport:       { v: "2.3", note: "match & replace: an unmappable terms-of-use / custom auth-strength id falls back to the ids of the policy being replaced (they are tenant-valid by definition) instead of failing the upgrade with a bare 400; failed updates now say explicitly that the current policy is untouched;dependencies first, persona remapping, placeholder resolution, change report, on-screen report, claims-challenge step-up, up-front consent, import by persona, dependency scoping to selection, terms-of-use checklist, assignment mode (deployment groups or match & replace: keep the current policy's assignment and switch its superseded version Off), Workload ID licence check (workload-identity policies held back when the tenant lacks the SKU), retry without app references the tenant cannot resolve" },
};
