// ======================================================================
// Build stamp. Shown on the sign-in screen and in the footer so you can
// tell at a glance whether the deployed site is the version you pushed —
// GitHub Pages and the browser cache can both lag a commit behind.
//
// `build` matches the ?v= cache-busting number on every asset URL in
// index.html; bump both together when releasing.
// ======================================================================
const APP_BUILD = {
  version: "1.0",
  build: 216,
  date: "2026-08-10",
  get label() { return `v${this.version}.${this.build}`; },
  get full() { return `${this.label} · ${this.date}`; },
};

// Per-tool versions, keyed by the tile id in index.html. Each tool moves at
// its own pace, so a tenant-side reviewer can tell which one changed since
// they last looked without diffing the whole app. Bump the tool you touched.
const TOOL_VERSIONS = {
  toolPolicies:     { v: "2.3", note: "list and summary say how many more include entries there are instead of showing only the first;usable on a phone — non-sticky toolbar, single-column policy cards, scrolling state filters, scrolling list table, two-row action bar;cards / list / settings matrix, persona grouping, dependency inspector, full-screen matrix, selection actions, delete with typed confirmation, per-policy what-if flow, per-persona apply flow, housekeeping (delete superseded Off versions)" },
  toolDocument:     { v: "1.4", note: "Word, PDF, PNG and PNG-bundle export with tenant branding" },
  toolAnalyze:      { v: "1.6", note: "users × policies impact matrix, group filters, standalone HTML report, scoped matrix columns" },
  toolGapCheck:     { v: "1.7", note: "Zero Trust scorecard (3 pillars, weighted 0-100 signals) on the summary and in the Markdown export; 7 new checks: risk-based-policy gaps, Microsoft-managed policy detection (incl. disabled phantom drafts), platform-scoping without an unknown-platform block, named-location hygiene, MFA client-app-type coverage, disabled resilience defaults, authentication-context / Protected Actions validation; bypass checks, persona × control matrix, deployed-but-Off state, Markdown export" },
  toolExclusions:   { v: "1.6", note: "exclusion × policy matrix (default, unmerged), effective-user view and risk review (governance flags per policy, patterns after Tiago S. Carvalho), click-to-filter rows and columns, group member list, CSV and Markdown" },
  toolValidator:    { v: "1.6", note: "per-policy sign-in simulation report ported from Jasper Baes' Conditional Access Validator — expected control per user/app/client/location/platform/risk, inverted 'no control' for excluded scope, report-only toggle, filter/search, Markdown export (no Maester code, representative placeholder users), click a policy name to open its card — out of BETA" },
  toolWhatIf:       { v: "1.0", note: "Entra Conditional Access What If tool re-implementation — simulate a sign-in (identity, resource, platform, client app, IP/country, device state, risks, auth flow) and get the policies that apply with their grant/session controls plus the policies that don't and the first unmet condition; named-location CIDR and country matching, Markdown export" },
  toolGroupUse:     { v: "0.4", note: "BETA — where an Entra group is actually used: 23 services across Entra ID (nesting, administrative units, directory roles incl. PIM eligibility, enterprise apps, group-based licensing, authentication methods policy, Conditional Access, access packages, admin-consent reviewers, registration state), Intune (enrolment restrictions, compliance, configuration profiles, scripts, app protection, app configuration, app assignments, Autopilot, Windows update profiles), Microsoft 365 (M365 group / Team) and Azure RBAC across subscriptions and management groups; one group or user, or a tenant-wide sweep with an unused-groups view; parent-group inheritance shown per hit; per-area consent; Markdown, standalone HTML and CSV export. 0.2: sweep rows open a popup built from the sweep data instead of re-scanning (with Deep analyze for parent expansion), HTML report added, Intune scripts now request DeviceManagementScripts.Read.All and entitlement management uses single-level expands with a candidate ladder (both were failing), and every failure says which permission and which role it needs. 0.3: sweep can be narrowed by name prefix / suffix / substring, and drilling into a group keeps the sweep loaded behind a Back button. 0.4: default sweep scope is the groups Conditional Access actually assigns — taken from the policies already in memory, no directory enumeration — with dangling references (an id a policy names but the directory no longer has) kept and flagged; summary chips ride in a sticky strip so the counts and filters stay reachable on a long result. After Jasper Baes' Microsoft Cloud Group Analyzer" },
  toolCompare:      { v: "1.0", note: "two or more users side by side: per-policy assignment (included / excluded and why / not targeted) with differences flagged, group and role membership diff, optional What-If sign-in scenario evaluated per user, differences-only toggle, Markdown export — out of BETA" },
  toolAudit:        { v: "1.5", note: "directory audit log of Conditional Access changes — policy, named location, authentication strength/context and terms-of-use edits with a field-level diff of what moved, actor and IP, kind/action filters, 7/30/90-day window, Markdown export, JSON snapshot export/compare, summary view — out of BETA" },
  toolSignins:      { v: "1.5", note: "search box suggests UPNs — the users and apps in the current result first, then the directory;Sign-ins (per sign-in) is the default view; usable on a phone (full-width search, swipeable policy chips, tighter cards); out of BETA; policy names open the policy card (as in List Policies); sticky policy label while scrolling an expanded policy's sign-ins; sign-in log × Conditional Access verdicts — sign-ins a policy failed (enforced) or would have failed (report-only, client-filtered and capped), grouped per policy with distinct users, affected apps and unmet grant controls; per-policy chips, user/app/IP search, 1/7/30-day window, one-click replay of a logged sign-in in What-If, CSV export (one line per sign-in × failing policy) and Markdown report" },
  toolBaseline:     { v: "1.8", note: "Limon-IT catalog, card and table views, number-clash detection, collapsible personas, catalog revision 2026-07-21, refresh, on-screen gap report" },
  toolBaselineJoey: { v: "1.1", note: "Joey Verlinden catalog 2026.6.1, verified against commit 38469a4" },
  toolMsLearn:      { v: "2.0", note: "17 documented checks, 14 buildable fixes, apply-in-tenant with service-principal creation and change report" },
  toolJson:         { v: "1.2", note: "policy zip including dependencies and terms-of-use PDFs" },
  toolProtect:      { v: "1.2", note: "several scoped administrators, comma-separated, each resolved and granted on its own with per-account outcomes in the report;scan on demand (▶ button) instead of on open, result persists across tab switches until an explicit rescan, a scan in flight survives navigation; standalone view of the exclusion-group protection workflow — restricted management administrative unit (create if missing or reuse), per-group protection status, optional AU-scoped Groups Administrator, explicit acknowledgement, Markdown report; the same workflow remains available as CA groups ⑥ Protect" },
  toolCaGroups:     { v: "2.3", note: "④ Assign targets directory roles as well as groups — include and exclude, with Microsoft’s 14-role privileged set as a quick pick;⑥ Protect takes several scoped administrators (comma-separated);🚫 Disable group nesting (BETA): Entra's beta disableNesting on a persona group so no group can be added as a member — three-state detection (disabled / allowed / not reported, since a plain read does not return it), the in-place PATCH attempted AND verified by reading the value back, rename + recreate + move user members + repoint policies only if Entra refuses and only behind a second typed confirmation, and a hard block when the group already contains nested groups;⑥ Protect: restricted management administrative unit for the CA exclusion groups — per-group protection status, create/reuse the restricted AU (isMemberManagementRestricted, immutable), optional AU-scoped Groups Administrator, explicit acknowledgement, Markdown report; ⑤ Import members: bulk-add pilot users from a CSV (UPN + optional multi-persona column) with persona→group auto-mapping, membership pre-check, review-before-apply and a Markdown change report;baseline group check, creation, members × groups matrix, and policy assignment in one tool, per-group member scan, manual group builder, remove-group action, final confirm, assignment change report, pick-by-persona, TeamsSharedDevices template, per-row create, recreate-role-assignable, convert-to-dynamic (in place or rename + recreate + reassign)" },
  toolLocations:    { v: "1.4", note: "named locations inventory with policy usage; create/edit/delete IP-range and country locations, CIDR + ISO-code validation, trusted-flag impact warning, typed confirm when a referenced location is deleted, card grid + table view, per-location report with full policy usage, per-location and inventory Markdown, JSON config snapshot + compare — out of BETA" },
  toolState:        { v: "1.0", note: "On / report-only / Off switching" },
  toolImport:       { v: "2.3", note: "match & replace: an unmappable terms-of-use / custom auth-strength id falls back to the ids of the policy being replaced (they are tenant-valid by definition) instead of failing the upgrade with a bare 400; failed updates now say explicitly that the current policy is untouched;dependencies first, persona remapping, placeholder resolution, change report, on-screen report, claims-challenge step-up, up-front consent, import by persona, dependency scoping to selection, terms-of-use checklist, assignment mode (deployment groups or match & replace: keep the current policy's assignment and switch its superseded version Off), Workload ID licence check (workload-identity policies held back when the tenant lacks the SKU), retry without app references the tenant cannot resolve" },
};
