#!/usr/bin/env node
// Regenerates every file under tools/pim that is derived from the catalog
// (js/pimBaselineData.js) — run it after a catalog change, commit what it
// writes. tools/pimbaseline.test.cjs fails when a committed file differs from
// what this would write.
//
//   node tools/pim/generate.cjs
//
// Writes:
//   pim-baseline.json                 the whole framework for the baseline tenant
//                                     (cloudfellows.dev): every profile's groups
//   pim-baseline.<profile>.json       one config per profile, tenant-neutral
//   samples/easypim.<profile>.jsonc   the commented EasyPIM samples to copy and edit
//   pim-regions-template.json         the region template New-PimRegions.ps1 uses
//                                     when the regions file is a CSV
//   regions.csv                       the two demo regions of cloudfellows.dev
//   regions.cloudfellows.dev.json     the same, as ENCA's regions file
const fs = require("node:fs");
const path = require("node:path");
const root = path.join(__dirname, "..", "..");
const read = (f) => fs.readFileSync(path.join(root, f), "utf8");
const PB = new Function(read("js/pimbaseline.js") + ";return PimBaseline;")();
const CAT = new Function(read("js/pimBaselineData.js") + ";return PIM_BASELINE;")();

function files() {
  const out = {};
  const json = (o) => JSON.stringify(o, null, 2) + "\n";
  out["pim-baseline.json"] = json(PB.toOrchestrator(CAT, { domain: "cloudfellows.dev", everyProfile: true, meta: { tenant: "cloudfellows.dev" } }));
  for (const id of PB.profileIds(CAT)) {
    out[`pim-baseline.${id}.json`] = json(PB.toOrchestrator(PB.profile(CAT, id), { domain: "<tenant domain>" }));
    out[`samples/easypim.${id}.jsonc`] = PB.toSample(CAT, id);
  }
  const multi = PB.profile(CAT, "multi");
  const tpl = PB.toRegionsFile(multi, [], { domain: "<tenant domain>" });
  delete tpl.regions;
  tpl._comment = `${CAT.label} ${CAT.release} — the region TEMPLATE (never the regions): what tools/pim/New-PimRegions.ps1 instantiates per row of a regions.csv. Generated by tools/pim/generate.cjs; do not edit by hand.`;
  out["pim-regions-template.json"] = json(tpl);
  const csv = CAT.regions.example.replace(/contoso\.nl/g, "cloudfellows.dev");
  out["regions.csv"] = csv + "\n";
  const rows = PB.parseRegions(csv, CAT).rows;
  out["regions.cloudfellows.dev.json"] = json(PB.toRegionsFile(multi, rows, { domain: "cloudfellows.dev" }));
  return out;
}
module.exports = { files };

if (require.main === module) {
  for (const [name, body] of Object.entries(files())) {
    const p = path.join(__dirname, name);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    const before = fs.existsSync(p) ? fs.readFileSync(p, "utf8") : null;
    if (before !== body) { fs.writeFileSync(p, body); console.log(`${before === null ? "wrote  " : "updated"} tools/pim/${name}`); }
    else console.log(`same    tools/pim/${name}`);
  }
}
