const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const box={};vm.createContext(box);vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/policy-compare.js'),'utf8')+'\nglobalThis.api=PolicyCompare;',box);const api=box.api;
function pair(){return ['1.0.2','1.0.3'].map((v,i)=>({id:'p'+i,name:'CA008-SESSION v'+v,raw:{id:'p'+i,displayName:'CA008 v'+v,state:i?'enabledForReportingButNotEnforced':'enabled',conditions:{users:{includeGroups:['deploy'],excludeGroups:i?['emergency','shared','service']:['emergency','shared']},platforms:{includePlatforms:i?['windows','macOS','linux']:['windows','macOS']}},sessionControls:{signInFrequency:{isEnabled:true,value:3,type:'hours'}}}}));}
test('Version comparison shows precise added exclusion and platform plus name and state',()=>{const r=api.compare(...pair());assert.equal(r.complete,true);assert.equal(r.changed,4);const fields=r.rows.filter(x=>x.changed).map(x=>x.path);assert.ok(fields.includes('conditions.users.excludeGroups'));assert.ok(fields.includes('conditions.platforms.includePlatforms'));assert.ok(fields.includes('state'));const html=api.render(r,{resolve:id=>id==='service'?'Service accounts':id});assert.match(html,/Added:.*Service accounts \(service\)/);assert.match(html,/On/);assert.match(html,/Report-only/);assert.doesNotMatch(html,/data-hk-field="sessionControls.signInFrequency.value"/);assert.match(api.render(r,{onlyChanges:false}),/data-hk-field="sessionControls.signInFrequency.value"/);});
test('Configuration normalization agrees across ordering, metadata and unknown preview properties',()=>{const ps=pair();ps[1]=structuredClone(ps[0]);ps[1].raw.conditions.users.excludeGroups.reverse();ps[1].raw.modifiedDateTime='tomorrow';ps[1].raw['@odata.context']='new context';assert.equal(api.compare(...ps).changed,0);ps[1].raw.preview={newField:['enabled']};assert.equal(api.compare(...ps).changed,1);assert.match(api.render(api.compare(...ps)),/preview.newField/);});
test('Removed assignments are directional and equal directory names do not hide distinct IDs',()=>{const ps=pair();ps[1].raw.conditions.users.excludeGroups=['replacement'];const html=api.render(api.compare(...ps),{resolve:()=> 'Same display name'});assert.match(html,/Removed:.*Same display name \(emergency\)/);assert.match(html,/Added:.*Same display name \(replacement\)/);});
test('Missing payload cannot be presented as equivalence or as removed protections',()=>{const ps=pair();delete ps[1].raw;const r=api.compare(...ps);assert.equal(r.complete,false);assert.ok(r.rows.every(x=>['state','displayName'].includes(x.path)));assert.match(api.render(r),/details are incomplete/);});
test('Null, absent, false and empty collections stay distinguishable; object type changes do not crash',()=>{const ps=pair();ps[0].raw.preview={mode:false,scope:null,empty:[],object:{k:'value'}};ps[1].raw.preview={mode:'false',empty:null,object:'new'};const r=api.compare(...ps);for(const key of ['mode','scope','empty','object'])assert.equal(r.rows.find(x=>x.path==='preview.'+key).changed,true);assert.match(api.render(r),/Not configured/);assert.match(api.render(r),/None \(empty list\)/);});
test('Comparison escapes policy names, unknown fields, resolved labels and filter strings',()=>{const ps=pair();ps[0].name='<img src=x onerror=alert(1)>';ps[0].raw.conditions.devices={deviceFilter:{rule:'<script>alert(1)</script>'}};const html=api.render(api.compare(...ps),{resolve:()=>'<svg onload=alert(1)>'});assert.doesNotMatch(html,/<img|<svg|<script/);assert.match(html,/&lt;script&gt;/);});
test('Session control value change and arrays of objects compare without order noise',()=>{const ps=pair();ps[0].raw.preview=[{a:1,b:2},{a:2,b:1}];ps[1].raw.preview=[{b:1,a:2},{b:2,a:1}];ps[1].raw.sessionControls.signInFrequency.value=6;const r=api.compare(...ps);assert.equal(r.rows.find(x=>x.path==='preview').changed,false);const row=r.rows.find(x=>x.path==='sessionControls.signInFrequency.value');assert.equal(row.left,3);assert.equal(row.right,6);assert.equal(row.changed,true);});
test('A whole block against null is compared setting by setting, a strength is one named row, @odata annotations are not settings (25376)',()=>{
 const ps=pair();
 ps[0].raw.grantControls={operator:'OR',builtInControls:[],'authenticationStrength@odata.context':'https://graph.microsoft.com/beta/$metadata#policies(p0)/grantControls/authenticationStrength/$entity',authenticationStrength:{id:'00000000-0000-0000-0000-000000000002',displayName:'Multifactor authentication',description:'x',allowedCombinations:['fido2','password,sms'],combinationConfigurations:[],'combinationConfigurations@odata.context':'https://graph.microsoft.com/beta/x',createdDateTime:'2021-12-01T08:00:00Z',policyType:'builtIn'}};
 ps[1].raw.grantControls={operator:'OR',builtInControls:['block'],'authenticationStrength@odata.context':'https://graph.microsoft.com/beta/$metadata#policies(p1)/grantControls/authenticationStrength/$entity',authenticationStrength:null};
 ps[0].raw.sessionControls={applicationEnforcedRestrictions:null,cloudAppSecurity:null,persistentBrowser:null,signInFrequency:{authenticationType:'primaryAndSecondaryAuthentication',frequencyInterval:'everyTime',isEnabled:true,type:null,value:null}};
 ps[1].raw.sessionControls=null;
 const r=api.compare(...ps);const paths=r.rows.map(x=>x.path);
 assert.ok(paths.every(p=>!/@odata/.test(p)),'no @odata row');
 assert.equal(r.rows.filter(x=>x.path==='grantControls.authenticationStrength').length,1,'one strength row');
 assert.equal(r.rows.find(x=>x.path==='sessionControls.applicationEnforcedRestrictions').changed,false,'null against null is not a change');
 assert.equal(r.rows.find(x=>x.path==='sessionControls.signInFrequency.isEnabled').changed,true);
 assert.equal(r.rows.find(x=>x.path==='sessionControls.signInFrequency.frequencyInterval').changed,true);
 const html=api.render(r);
 assert.match(html,/Multifactor authentication \(00000000-0000-0000-0000-000000000002\)/);
 assert.doesNotMatch(html,/allowedCombinations|"isEnabled"|\{\s*"/,'no raw JSON in the table');
 assert.match(html,/Session controls · Sign-in frequency · Enabled/);
 // two policies on the SAME strength differ only by the annotation naming their own id: not a configuration difference
 const same=pair();same[1]=structuredClone(same[0]);same[0].raw.grantControls={operator:'OR',builtInControls:[],'authenticationStrength@odata.context':'…p0…',authenticationStrength:{id:'s1',displayName:'S'}};same[1].raw.grantControls={operator:'OR',builtInControls:[],'authenticationStrength@odata.context':'…p1…',authenticationStrength:{id:'s1',displayName:'S'}};
 assert.equal(api.signature(api.config(same[0])),api.signature(api.config(same[1])));
});
