const {test}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),source=f=>fs.readFileSync(path.join(root,'js',f),'utf8');
const quiet={log(){},warn(){},error(){}};
function load(file,symbol,extra={}){const box=vm.createContext({console:quiet,URL,Set,Map,...extra});vm.runInContext(source(file)+'\nglobalThis.result='+symbol,box);return box.result;}
class Msal {async initialize(){}async handleRedirectPromise(){return null;}async acquireTokenSilent(){return {accessToken:'fixture'};}}
async function graph(fetch,extra={}) {const g=load('graph.js','Graph',{AUTH_CONFIG:{clientId:'fixture',authority:'fixture',scopes:['Directory.Read.All'],graphBase:'https://graph.microsoft.com/beta'},window:{location:{origin:'http://localhost',pathname:'/'}},msal:{PublicClientApplication:Msal},fetch,setTimeout,clearTimeout,...extra});await g.init();return g;}
const response=body=>({ok:true,status:200,headers:{get:()=>null},json:async()=>body});
const raw=(users={includeUsers:['All']})=>({id:'p',displayName:'P',state:'enabled',conditions:{users,applications:{includeApplications:['All']}},grantControls:{operator:'OR',builtInControls:['mfa']}});
const view=p=>({raw:p,seq:'p',grant:{controls:['mfa'],op:'OR'}});
const app=source('app.js'),CaScope=load('cascope.js','CaScope');
test('ARM succeeds after a 200 response',async()=>{const g=await graph(async()=>response({value:['ok']}));assert.equal((await g.aget('https://management.azure.com/subscriptions?api-version=2022-12-01')).value[0],'ok');});
test('batch honours the full Retry-After, including waits longer than a minute',async()=>{let calls=0,wait=0;const g=await graph(async()=>response({responses:++calls===1?[{id:'1',status:429,headers:{'Retry-After':'120'}}]:[{id:'1',status:200,body:{value:[]}}]}),{setTimeout:(fn,ms)=>{wait+=ms;fn();}});await g.gbatch([{id:'1',url:'/users'}]);assert.equal(wait,120000);assert.equal(calls,2);});
test('final-page overflow is partial even without a next link',async()=>{const g=await graph(async()=>response({value:Array.from({length:600},(_,id)=>({id}))}));const r=await g.readPages('/users', {cap:500});assert.equal(r.items.length,500);assert.equal(r.observed,600);assert.equal(r.capped,true);assert.equal(r.complete,false);});
test('pager follows every continuation and exposes complete coverage',async()=>{let n=0;const g=await graph(async()=>response(++n===1?{value:[{id:1}],'@odata.nextLink':'https://graph.microsoft.com/v1.0/users?$skiptoken=two'}:{value:[{id:2}]}));const r=await g.readPages('/v1.0/users');assert.equal(r.complete,true);assert.equal(r.items.length,2);assert.equal(r.pages,2);});
test('malformed and repeated pages cannot become complete results',async()=>{for(const body of [{}, {value:[],'@odata.nextLink':'/users'}]){const g=await graph(async()=>response(body));await assert.rejects(g.readPages('/users'),/collection|Repeated/);}});
test('identical in-flight reads share one request',async()=>{let calls=0,finish;const g=await graph(()=>{calls++;return new Promise(r=>finish=r);});const a=g.gget('/users'),b=g.gget('/users');await new Promise(r=>setImmediate(r));finish(response({value:[]}));await Promise.all([a,b]);assert.equal(calls,1);});
test('read concurrency is bounded at four',async()=>{let active=0,max=0;const g=await graph(async()=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,5));active--;return response({value:[]});});await Promise.all(Array.from({length:12},(_,i)=>g.gget('/users?i='+i)));assert.equal(max,4);});
test('stopping a queued read removes it before a network call',async()=>{const finish=[];let calls=0;const g=await graph(()=>{calls++;return new Promise(r=>finish.push(r));});const busy=Array.from({length:4},(_,i)=>g.gget('/users?i='+i));await new Promise(r=>setImmediate(r));const ctl=new AbortController(),queued=g.gget('/users?queued',null,{signal:ctl.signal});ctl.abort();await assert.rejects(queued,e=>e.stopped);finish.forEach(r=>r(response({value:[]})));await Promise.all(busy);assert.equal(calls,4);});
test('stop interrupts a request and a throttled retry wait',async()=>{const ctl=new AbortController();let calls=0;const g=await graph(async()=>{calls++;return {ok:false,status:429,headers:{get:()=> '120'},json:async()=>({})};});const pending=g.gget('/users',null,{signal:ctl.signal});await new Promise(r=>setImmediate(r));ctl.abort();await assert.rejects(pending,e=>e.stopped);assert.equal(calls,1);});
test('readPages checks a stop requested during the last response',async()=>{const ctl=new AbortController();const g=await graph(async()=>{ctl.abort();return response({value:[{id:1}]});});await assert.rejects(g.readPages('/users',{signal:ctl.signal}),e=>e.stopped);});
test('Compare uses the shared external type, tenant and legacy token semantics',()=>{const c=load('compare.js','Comparer',{CaScope});const user={id:'u',guest:true,guestOrExternalUserType:'b2bCollaborationGuest',homeTenantId:'other',names:{},groupIds:new Set(),roleIds:new Set()};for(const p of [raw({includeUsers:['GuestsOrExternalUsers']}),raw({includeGuestsOrExternalUsers:{guestOrExternalUserTypes:'serviceProvider',externalTenants:{membershipKind:'enumerated',members:['partner']}}})]){assert.equal(c.assignmentRows(c.buildLookup([view(p)]),[user])[0].states[0].s,CaScope.of(p,user).state);}});
test('Compare exports unknown scope and keeps indeterminate scenarios in the matrix',()=>{const WhatIfEval=load('whatifeval.js','WhatIfEval',{CaScope}),c=load('compare.js','Comparer',{CaScope,WhatIfEval});const user={id:'u',name:'User',guest:true,names:{},groupIds:new Set(),roleIds:new Set()};const p=raw({includeGuestsOrExternalUsers:{guestOrExternalUserTypes:'serviceProvider'}});const rows=c.assignmentRows(c.buildLookup([view(p)]),[user]);assert.equal(rows[0].states[0].s,'unknown');assert.match(c.assignmentTable(rows,[user],false),/>\?<\/span>/);const scenario=c.scenario([p],[user],{appId:'a'}, {names:{}});assert.equal(scenario.perUser[0].complete,false);assert.equal(scenario.rows[0].cells[0].s,'unknown');});
async function copyFixture({unread=false,failAdd=false,missing=false}={}){
 const writes=[];let reads=0;const box=vm.createContext({console:quiet,AUTH_CONFIG:{scopes:[]},MEMBER_MOVE_SCOPES:[],Graph:{ggetAll:async()=>{if(unread)throw Error('403');return ++reads===1?[{id:'u','@odata.type':'#microsoft.graph.user'}]:missing?[]:[{id:'u'}];},gpost:async()=>{if(failAdd)throw Error('403 add');},gget:async()=>({conditions:{users:{includeGroups:['old']}}}),gpatch:async(url,body)=>writes.push(body)},r:{id:'old'},g:{id:'new'},p:{refs:{include:[{id:'p',name:'Policy'}],exclude:[]}},log:{failed:[],moved:[]},toast(){}});
 const start=app.indexOf('  async function moveGroupMembers(');vm.runInContext(app.slice(start,app.indexOf('  // ---- housekeeping:',start)),box);
 const tail=app.indexOf('        const mm = await moveGroupMembers(r.id, g.id,');const end=app.indexOf('\n      }\n      $("nestRcModal")',tail);
 let error;try{await vm.runInContext('(async()=>{'+app.slice(tail,end)+'})()',box);}catch(e){error=e;}
 return {writes,error};
}
test('group recreation keeps policy references when source read, copy or verification fails',async()=>{for(const flags of [{unread:true},{failAdd:true},{missing:true}]){const r=await copyFixture(flags);assert.ok(r.error);assert.equal(r.writes.length,0);}});
test('group recreation can switch references only after verified membership',async()=>{const r=await copyFixture();assert.equal(r.error,undefined);assert.equal(r.writes.length,1);assert.deepEqual(Array.from(r.writes[0].conditions.users.includeGroups),['new']);});
test('Exclusions computes all 600 users and refuses unread membership',async()=>{const ex=load('exclusions.js','Exclusions',{Graph:{ggetAll:async()=>Array.from({length:600},(_,id)=>({id:'u'+id,displayName:'User '+id})),gbatch:async()=>({})}});const m=await ex.resolve(ex.collect([raw({includeUsers:['All'],excludeGroups:['g']})]));assert.equal(ex.effectiveUsers(m).length,600);const bad=load('exclusions.js','Exclusions',{Graph:{ggetAll:async()=>{throw Error('403');}}});await assert.rejects(bad.resolve(bad.collect([raw({excludeGroups:['g']})])),/incomplete/);});
const WhoIs=load('whois.js','WhoIs',{CaScope});
const waveArgs=()=>({group:{id:'wave',displayName:'Wave'},members:[{id:'u',displayName:'User'}],groupMembers:new Map(),roleMembers:new Map(),names:{},vms:[view(raw({includeUsers:['All'],excludeGroups:['ex']}))],dgGroups:[],records:null,days:7});
test('Wave preserves unknown membership instead of claiming inclusion',()=>{const wave=load('wave.js','Wave',{WhoIs});const r=wave.analyze({...waveArgs(),groupsComplete:false});assert.equal(r.members[0].states[0].st.s,'unknown');assert.equal(r.rows[0].unknown,1);assert.equal(r.incomplete,true);assert.match(wave.toMd(r),/INCOMPLETE/);});
test('Wave referenced groups read beyond the first 999 members',async()=>{const box=vm.createContext({isDemo:false,Graph:{mapLimit:async(a,n,fn)=>Promise.all(a.map(fn)),ggetAll:async()=>Array.from({length:1001},(_,i)=>({id:'u'+i})),gget:async()=>({displayName:'Group'})},wvProg:{check(){},tick(){}}});const a=app.indexOf('  async function wvMemberSets('),b=app.indexOf('  async function runWave(',a);vm.runInContext(app.slice(a,b)+'\nglobalThis.read=wvMemberSets',box);const r=await box.read(['g']);assert.equal(r.out.get('g').has('u1000'),true);assert.equal(r.errors.length,0);});
function progress(){let now=1000;const nodes={xPgTxt:{textContent:''},xPgBar:{style:{},classList:{toggle(){}}}};const box=vm.createContext({console:quiet,tenantId:'fixture',policiesReadAt:1,isDemo:false,Graph:{},esc:s=>String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"),Date:{now:()=>now},PROG_REG:{},$:id=>nodes[id],setInterval:()=>1,clearInterval(){},AbortController,document:{querySelectorAll:()=>[]}});const a=app.indexOf('  function makeProgress('),b=app.indexOf('  // The audit range selector',a);vm.runInContext(app.slice(a,b)+'\nglobalThis.result=makeProgress("x")',box);return {p:box.result,nodes,advance:ms=>now+=ms};}
test('progress shows first-response elapsed time and never treats a record/page cap as percent',()=>{const h=progress();h.p.start(25,'users','page');h.advance(30000);assert.match(h.p.panel('Read'),/30s/);h.p.tick(999,1);assert.notEqual(h.nodes.xPgBar.style.width,'100%');h.p.start(10,'groups','group');h.p.tick(5,5);assert.equal(h.nodes.xPgBar.style.width,'50%');assert.match(h.p.panel('Read'),/30s/);h.p.detail('<img src=x onerror=alert(1)>');assert.match(h.p.panel('Read'),/&lt;img/);assert.doesNotMatch(h.p.panel('Read'),/<img/);});
test('progress Stop aborts the owned read and stays visibly stopped before page one',()=>{const h=progress();h.p.start(0);h.p.requestStop();assert.equal(h.p.signal.aborted,true);assert.match(h.p.panel('Read'),/stopping/);assert.throws(()=>h.p.check(),e=>e.stopped);});
test('late log responses never overwrite the new source cache',async()=>{let finish;const box=vm.createContext({console:quiet,logSource:'entra',logInflight:null,logCache:null,logCacheUsable:()=>false,logReadKey:(d,s)=>JSON.stringify([d,s||box.logSource]),isGraphLogSource:s=>s==='entra',ReportImpact:{query:()=>'/signins'},SI_MAX:10000,Date,setInterval,clearInterval});const a=app.indexOf('  async function readSignInWindow('),b=app.indexOf('  const logAgeLabel',a);vm.runInContext(app.slice(a,b)+'\nglobalThis.read=readSignInWindow',box);const pending=box.read(7,{st:{},fetchAll:()=>new Promise(r=>finish=r)},true);box.logSource='hunt';finish([{id:'from-entra'}]);await assert.rejects(pending,/discarded/);assert.equal(box.logCache,null);});
const Capabilities=load('capabilities.js','Capabilities');
test('P1 product evidence does not imply P2, Intune or Workload Premium',()=>{const e=Capabilities.fromSkus([{servicePlans:[{servicePlanId:'41781fb2-bc02-4b7c-bd55-b576c07bb09d',provisioningStatus:'Success'}]}]);assert.equal(e.p1,true);assert.equal(e.p2,false);assert.equal(e.intune,false);assert.equal(e.workload,false);assert.equal(Capabilities.check(raw(),e).ok,true);const risk=raw();risk.conditions.userRiskLevels=['high'];assert.equal(Capabilities.check(risk,e).ok,false);});
test('unknown and suspended entitlement cannot pass policy preflight',()=>{for(const skus of [null,[{capabilityStatus:'Suspended',servicePlans:[{servicePlanId:'41781fb2-bc02-4b7c-bd55-b576c07bb09d'}]}]])assert.equal(Capabilities.check(raw(),Capabilities.fromSkus(skus)).ok,false);});
test('replacement preflight reserves staging slots and checks every selected policy',()=>{assert.equal(Capabilities.plan([raw()],{p1:true},240).ok,false);assert.equal(Capabilities.plan([raw(),raw()],{p1:true},239).ok,false);assert.equal(Capabilities.plan([raw()],{p1:true},239).ok,true);assert.equal(Object.keys(Capabilities.tools).length,40);});
test('policy guard blocks HTTP writes while leaving reads accessible',async()=>{let calls=0;const g=await graph(async()=>{calls++;return response({value:[]});});g.setPolicyGuard(async()=>{throw Error('licence required');});await assert.rejects(g.gpost('/identity/conditionalAccess/policies',raw()),/licence required/);await assert.rejects(g.gpatch('/identity/conditionalAccess/policies/p',{state:'enabled'}),/licence required/);assert.equal(calls,0);await g.gget('/identity/conditionalAccess/policies');assert.equal(calls,1);});
test('P1 non-interactive option explicitly selects the beta event types',()=>{const r=load('reportimpact.js','ReportImpact');assert.match(decodeURIComponent(r.query(7,true)),/\/beta\/.*nonInteractiveUser/);assert.match(r.query(7),/^\/v1\.0\//);});
test('analysis worker produces the same complete Wave result',()=>{const messages=[];let box;box=vm.createContext({console:quiet,URL,Set,Map,self:{location:{href:'http://localhost/js/analysis-worker.js?v=fixture'},postMessage:m=>messages.push(m)},importScripts:(...files)=>files.forEach(f=>vm.runInContext(source(f.split('?')[0]),box))});vm.runInContext(source('analysis-worker.js'),box);const a=waveArgs();box.self.onmessage({data:{kind:'wave',args:a}});assert.equal(messages.at(-1).error,undefined);const expected=load('wave.js','Wave',{WhoIs}).analyze(a);assert.equal(messages.at(-1).result.members.length,expected.members.length);assert.equal(messages.at(-1).result.rows[0].reach,expected.rows[0].reach);});
test('policy guards also cover batch writes and deleted-policy restores',async()=>{let calls=0;const g=await graph(async()=>{calls++;return response({value:[]});});g.setPolicyGuard(async()=>{throw Error('preflight blocked');});await assert.rejects(g.gbatch([{id:'1',method:'PATCH',url:'/identity/conditionalAccess/policies/p',body:{state:'enabled'}}]),/preflight blocked/);await assert.rejects(g.gpost('/identity/conditionalAccess/deletedItems/policies/p/restore',{}),/preflight blocked/);assert.equal(calls,0);});
test('Wave partial sign-in evidence remains incomplete in both exports',()=>{const wave=load('wave.js','Wave',{WhoIs});const r=wave.analyze({...waveArgs(),logsComplete:false});assert.equal(r.incomplete,true);assert.match(wave.toMd(r),/INCOMPLETE/);assert.match(wave.toCsv(r),/evidence_complete,member_limit/);assert.match(wave.toCsv(r),/false,0$/);});
test('queued analysis cancellation rejects without starting a third worker',async()=>{const instances=[];class Worker{constructor(){instances.push(this);}postMessage(){}terminate(){this.terminated=true;}}const jobs=load('analysis-jobs.js','AnalysisJobs',{document:{currentScript:{src:'http://localhost/js/analysis-jobs.js?v=test'}},Worker});const a=jobs.run('impact',{}),b=jobs.run('impact',{});const controller=new AbortController();const c=jobs.run('impact',{}, {signal:controller.signal});controller.abort();await assert.rejects(c,e=>e.stopped);assert.equal(instances.length,2);instances[0].onmessage({data:{result:1}});instances[1].onmessage({data:{result:2}});assert.deepEqual(await Promise.all([a,b]),[1,2]);});
test('analysis refuses an oversized matrix before allocating a worker',async()=>{const jobs=load('analysis-jobs.js','AnalysisJobs',{document:{currentScript:{src:'http://localhost/js/analysis-jobs.js'}}});await assert.rejects(jobs.run('analyze',{users:{length:250000},lookup:{length:240}}),/2 million/);});
test('progress clock resets for a new run after stop',()=>{const h=progress();h.p.start(0);h.advance(30000);h.p.stop();h.p.start(0);assert.match(h.p.panel('Read'),/response · 0s/);});
